### ISSUE TITLE
Add a map showing all the countries that fellows are located in

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.0-portfolio#12]
Underneath projects and fellows, have an interactive map that displays where everyone is located.

- [ ] When you click on the pin location for that fellow, it gives you a card with information about the fellow (similar to the fellow section

You can chose to have pins or use circular profile pictures to show where everyone is on the map. You could remove the fellows section and replace it with the map.

**Comment by Nishtha0801** [comment]
We would like to work on it, Please assign this issue to us.

Team members: @thedevyansh @Nishtha0801 @yogi2103

**Comment by rudranshsharma123** [comment]
Hello our team { @Naman-1234 , @ManishaJhunjhunwala , @HugoCL , @rudranshsharma123  } would like to work on this issue

**Comment by yogi2103** [comment]
Hi @grace-omotoso, I'm from team2{ @Nishtha0801 @thedevyansh @yogi2103 } and we would like to work upon this as all the tasks we hadtaken have been almost completed by other members and I'm already working on it.
