### ISSUE TITLE
Add social icons for fellows

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.0-portfolio#13]
At the moment, it only displays the fellow name and location. To help people network, we should add social icons to each of the fellow cards.

![Screenshot 2021-09-30 at 14 24 40](https://user-images.githubusercontent.com/34094921/135463524-d5ddd708-920c-4fc0-ba87-02ca80186d9e.png)
- [x] Add LinkedIn icons to the card
- [x] Add Twitter icons to the card
- [x] Add Resume icons to the card
- [x] Add GitHub icons to the card

**Comment by Manasvi070902** [comment]
We would like to work on this issue!

Regards
Team 4( @Priyaraj17 , @Raunakk02 , @Manasvi070902 )
