### ISSUE TITLE
Add work experience timeline and education qualifications

### ISSUE THREAD

**Issue by Apurva-tech** [MLH-Fellowship/pod-4.1.0-portfolio#23]
## Things to complete: 

- [ ] Create a timeline for the fellow experience section, for example, his/her internship or work experience 
- [ ] The fellow can showcase volunteer work as a timeline. 
- [ ] Add education qualification details in the form of cards. 

Please assign this issue to Team 3. 
Regards, 
(@Apurva-tech, @AshAman999, @iamakkkhil, and @Henokaa)

**Comment by grace-omotoso** [comment]
@Apurva-tech you need to check with me before adding a new issue. Please, reach out on discord so we can discuss. Thanks
