### ISSUE TITLE
Add header background

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.0-portfolio#5]
At the moment, the header background is a colour. Have an option to add an image that's easy to swap to something else and works on multiple screen sizes.

**Comment by thedevyansh** [comment]
We would like to work on this issue.

Team members: @thedevyansh @Nishtha0801 @yogi2103

**Comment by rudranshsharma123** [comment]
Hello, our team { @Naman-1234  @HugoCL @ManishaJhunjhunwala @rudranshsharma123 } would like to work on this issue
